### ISSUE TITLE
YAML Configuration Validator

### ISSUE THREAD

**Issue by kestred** [Astron/Astron#152]
The YAML configuration file read-in by the Astron daemon should do config-file validation before attempting to initialize the daemon.

As an example of the kind of things it might check for, in the following example
file, it should detect a number of errors automatically:
- ~~in the `general` group there is no attribute of type `dc_file` [note: in this example the correct attribute is `dc_files`].~~
- ~~in the `messagedirector` group, `127.0.0.1-57123` is not a valid bind address~~
- ~~in the `database` role, Astron was not compiled with a database backend of type `yam`.~~
- in the `database` role, the attribute `9000000000` is out of the range of do_ids for Astron (compiled with 32-bit do_ids) [note: in this example, it should use `sizeof(doid_t)` or `DOID_MAX`/`DOID_MIN` to detect max and min values for do_ids.]
- ~~in the `dbss` role, the do_id `976` is reserved by Astron proper.~~
- ~~in the `dbss` role, range `[???, 200000000]` declared without a minimum value [note: in this example, there is an unwanted `-` before the `max` attribute].~~
- ~~in the `roles` group, Astron was not compiled with the role `foo`~~
- ~~in the `roles` group, role with attribute `qux` did not specify the attribute `type`~~

**Example File:** _example.yaml_

``` yaml
general:
    dc_file:
        - "/path/to/file/test.dc"

messagedirector:
    bind: 127.0.0.1-57123

roles:
    - type: database
      control: 402001
      generate:
        min: 100000000
        max: 9000000000
      engine:
        type: yam
        foldername: /tmp/database

    - type: dbss
      database: 402001 # The channel of the associated database
      ranges:
        - min: 976
        - max: 200000000

    - type: foo
      bar: "baz"

    - qux: quux
```
