### ISSUE TITLE
Interest: add_interest in CA configuration has no effect

### ISSUE THREAD

**Issue by Schwarzbaer** [Astron/Astron#280]
From my astrond.yml:

```
roles:
    - type: clientagent
      client:
          add_interest: disabled
```

However, when running the client:
:DoInterestManager(warning): handleInterestDoneMessage: handle not found: 0
